site_name: BruTile Documentation
theme:
  name: 'material'
  features:
    - content.action.edit
nav:
  - 'index.md'
  - 'getting-started.md'
repo_url: https://github.com/BruTile/BruTile/
edit_uri: blob/master/documentation/mkdocs/docs
