//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: AssemblyVersion("0.9.8")]
[assembly: AssemblyFileVersion("0.9.8")]

// Generated by the MSBuild WriteCodeFragment class on 3/28/2014 4:30:07 PM.

