name: Build BruTile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.402
    - name: Build with dotnet
      run: dotnet build BruTile-Build.sln --configuration Release
