name: Build on Windows

on:
  push:
    branches: [ '**' ]
    paths-ignore:
      - 'documentation'
  pull_request:
    branches: [ '**' ]
    paths-ignore:
      - 'documentation'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    env:
      SOLUTION: 'BruTile.sln'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            8.0.4xx
            9.0.x
    - name: Build
      run: dotnet build $SOLUTION --configuration Release -p:Version=$(git describe --tags)
    - name: check the formatting
      run: dotnet format BruTile.sln --verbosity normal --verify-no-changes --exclude BruTile/Wmts # Exclude Wmts because of generated EPSG data. Perhaps the data should be move to a separate file.
    - name: Test
      run: dotnet test $SOLUTION --configuration Release -p:Version=$(git describe --tags) --no-restore --verbosity normal
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: nupkg
        path: BruTile*/bin/Release/*.nupkg
