name: Release Nugets

on:
  workflow_dispatch:
    inputs:
      release_nuget:
        description: 'release to nuget.org'
        required: true
        type: boolean 

jobs:
  build:

    env:
      SOLUTION: 'BruTile.sln'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Prevent a shallow clone to allow git describe --tags

      # The version tag needs to be set before the release. If not if will fail on nuget publish.
    - name: Set VERSION_OF_RELEASE to last tag
      run: |
        echo ("VERSION_OF_RELEASE=" + $(git describe --tags --abbrev=0)) >> $env:GITHUB_ENV
        echo "${{ env.VERSION_OF_RELEASE }}"

    - name: Restore dependencies
      run: dotnet restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            8.0.4xx
            9.0.x
    - name: Build
      # The nupkgs will be built because the projects have GeneratePackageOnBuild set to true. 
      # The dlls and nupkgs will be built 'inputs.release_version' as version, overriding the version number in the Directory.Build.props.
      run: dotnet build $SOLUTION --configuration Release -p:Version=${{ env.VERSION_OF_RELEASE }} --no-restore -p:PackageOutputPath="${{ github.workspace }}/nugets"

    - name: Test
      run: dotnet test $SOLUTION --configuration Release --no-restore --verbosity normal -p:Version=${{ env.VERSION_OF_RELEASE }}
 
    - name: Upload nugets
      uses: actions/upload-artifact@v4
      with:
      # Upload the 'nugets' folder as artifact
        name: packages
        path: nugets/*.nupkg

    - name: Publish
      if: ${{ inputs.release_nuget }} 
      run: dotnet nuget push "nugets\**\*.nupkg" --source 'https://api.nuget.org/v3/index.json' --api-key ${{ secrets.NUGET_APIKEY }}