name: Release Nugets

on:
  workflow_dispatch:
    inputs:
      release_nuget:
        description: 'release to nuget.org'
        required: true
        type: boolean 
      release_version:
        description: 'The version of this release in semver format.'
        required: true
    
jobs:
  build:

    env:
      SOLUTION: 'BruTile.sln'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.402

    - name: Build
      # The nupkgs will be built because the projects have GeneratePackageOnBuild set to true. 
      # The dlls and nupkgs will be built 'inputs.release_version' as version, overriding the version number in the Directory.Build.props.
      run: dotnet build $SOLUTION --configuration Release -p:Version=${{ inputs.release_version }} --no-restore /p:PackageOutputPath="${GITHUB_WORKSPACE}/nugets"

    - name: Test
      run: dotnet test $SOLUTION --configuration Release --no-restore --verbosity normal -p:Version=${{ inputs.release_version }}
    
    # todo: Tag with the version as part of the release.
    #  if: ${{ inputs.release_nuget }} 
    #  run: |
    #    git tag ${{ inputs.release_version }}
    #    git push --tags
    
    - name: Publish
      if: ${{ inputs.release_nuget }} 
      run: |
        nuget push "${GITHUB_WORKSPACE}\nugets\**\*.nupkg" -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_APIKEY}}